sudo: false
language: scala
scala:
- 2.12.5
jdk:
- oraclejdk8

stages:
  - name: build
  - name: publish
    if: ((branch = master) AND (type != pull_request)) OR (tag IS present)

jobs:
  include:
    - stage: build
      script: sbt ++$TRAVIS_SCALA_VERSION test
    - stage: publish
      script: sbt ++$TRAVIS_SCALA_VERSION releaseEarly;

before_install:
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then 
    openssl aes-256-cbc -K $encrypted_054593f98bbe_key -iv $encrypted_054593f98bbe_iv -in travis/secrets.tar.enc -out travis/secrets.tar -d;
    tar xv -C travis -f travis/secrets.tar; 
  fi

env:
  global:
  - secure: "EahjkACzXGTrgAUVsLLZrQewDtX0UhMDOW1M+ji0/NYC+WjEsk/e/tOrncqIXR2nRKYRRL4pLJbw0bmyihQGiwED05FJugIzQSRiytdUy4CdDGsWH2KxB9S5oFfgl771FmrC5So70T2WOzffV5zBp38IVywXX8xx+bdDVP4vroNTA1rCKsTu3/r9qcWobb5Rx89X7n0scHhB4CaD08A7LeRIcx/E5A+E4N74vFtflZQTTsqzhMK8B/XxpB46scqHLOrYNYb6W6Jb0MQOrALWbZlP//qYf3A5hxElRXuD0WyK2r3LPZERXssCPmoHKSLaFKrLIBDedAQsWB1d4hd/hF/WY2mnWs6b3MCYRfx+OCfPmqSkKSL8oyxR3bHTBhvOLstDNi/PcWXeLLIirYbFUtLpm8vxyAyXK25W9Icrb/bbDXtfnMXmigMJLAqKwsFvuFt4bngDJZE5DCV1ESA8A5bGJtGZLA+6ONLR32OcmKciq5Nl0Wl6YHEl0iwm8SMxHrWF4N96nnWsVz0juCOBjVjhlfMISnSdBa3d7TzpcHNK7njK6D/YEjSuj9gvJOUYhhEvDejWrYP1FlpHMplDrKNeO0L1erw0+39uxVJD16GHnCY18PBq1MSVixI6IeOp24KFRbzLKqu5bzWdq4kGkMHsukL9Oh3WZYxu5XB/vcw="
  - secure: "hgfegKKM8DxYcrmLURksNZeiJBl+bbZE/+HihSk8fTTZANOcNaz9avoioxPnb6RnF04rLys8hYnJakEtgeLNL7rzVhuZybs5874/L3/PRRn7nM4zENklurrtrdaa0eQN+8mWgidVBwkwYWR1oaVFefFWXfjYYz8XYiXUUf+mPOzADsphDT2L+rPttbnaY/fArgwDq9Gh7tGDFJrAAicOjkxP7PGVrsFY43b7B9n8Mw4/owC3JA+fqmOXzK8y515WPlNk+nwf6A5yYYcX2KKjSkD/tSTr30jJOzgydHYso1A8texw90TcPWiK4dCVPcNvXAnLGlV50RvfsuKida3RZ6xLyWwtmyrU3oLVltcp0pLx0qtPNHBZSNdNqQSbRMznqCOME5Z09N9Iun3i6nGaknvK+S+oucW6UlRyNT81gY0MFsEn11qe311ZItTLLu4GP90s2zynIEu10yYcxsXaZJ/EHfJ5YhGd4ovpzm3Xvg+cczD9ZS5coR1XBaYn4xrrycYxijZ84p2BODFH8rOfNrV0yZNiUguAqOkL9UY3IlzfzxjGsMemucEBCNGmruWSTPipH+/C654oyNBlZfoPg+tLqcvZE1fFRMXkcfng8RgaNJNnzEiGpGwYu8XoqlvX06XCUdEA0tkvWYvn0wcA/KCNXecGGPZrJl6Zc2yBJIY="
  - secure: "jPHzXiqvzCIuw45Etcpk8LbW/T2Ga18ODWWaYKvfXDSVrEjETlffZ3xXhRLLo4NANyIlczWyu2NuMQLIhHcntH1EjWd3qtJs2wIIL/NZsX3HEJw397QWo9oQaWj/mvfV6SriItC6PsPmUNZfiCTyStZ5P/jgSdfGSMG8+SaPHnb9Mj4Yrrb9VJx9Npro9/sAhfp4EREIJ9fjQKR5pGEUxBj52LHrIfgspBrbtyDwf7jfiu+05loZtjOIwhsaqyZECBd5xKRTXikRi9o1WaAt1a9dA07VYJdrrAcsz27IKyMuUNqUHYnTB+2dwIQdnZz4otwiRM9f6VqYYIkSqho8HqEx3CvirPjAoyj4seXzWx5pwyBsx4TUjuXNyACxcuxh0ZtWjBZtaqhCTBxkhIhPsh9hPbA/2qzEZszNySUxiqZrNfUS+z4D/ubDi/j6NIgNqwtZIhoy/WvnlUBfcH8OnLiXxWWqIWDPNA2VXHrjkU1PSHNSprN5hBeoIaZTJhrb48RccfL6bIh1TlEoguaKPtBwovH78XZIPZuRoM7/LoXFWpRV8L0QQeXfVhHKzDygA9cxqD4AAAZGjyiN7YgPakfYOjw3INxsUpbNA45P57RwpzNstA/SBTAdA7cdEpmAoiXoigwVSgX8ntECJTqgpnsNAzpBGOLtd+3OvRK60JU="

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt
  - $HOME/.coursier
